//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVPPowerToolv2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVPPowerToolv2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;MVPPowerToolv2&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;HaPhuong&quot;)]
        ///[assembly: AssemblyProduct(&quot;MVPPowerToolv2&quot;)]
        ///[asse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ---ProjectName---.BasicClass
        ///{
        ///    public enum RowState { Insert, Update, Delete, Saved};
        ///
        ///    public class Bus
        ///    {
        ///        private RowState state = RowState.Insert;
        ///
        ///        public RowState State
        ///        {
        ///            get { return state; }
        ///            set { state = value; }
        ///        }
        ///
        ///        public void MakeUnChange()
        ///        {
        ///            this.state = RowS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusClass {
            get {
                return ResourceManager.GetString("BusClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSProject {
            get {
                return ResourceManager.GetString("CSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tbl.TABLE_NAME, col.COLUMN_NAME, col.DATA_TYPE
        ///FROM INFORMATION_SCHEMA.COLUMNS col
        ///JOIN (
        ///		SELECT tc.TABLE_NAME 
        ///		FROM INFORMATION_SCHEMA.TABLES tc
        ///		WHERE 
        ///			tc.TABLE_NAME != &apos;sysdiagrams&apos;
        ///		) tbl ON col.TABLE_NAME = tbl.TABLE_NAME
        ///.
        /// </summary>
        internal static string GetTablesDetailScript {
            get {
                return ResourceManager.GetString("GetTablesDetailScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    cu.CONSTRAINT_NAME, 
        ///    cu.COLUMN_NAME 
        ///FROM 
        ///    INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu 
        ///	JOIN (
        ///			SELECT tc.*
        ///            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc 
        ///            WHERE 
        ///                tc.TABLE_NAME = &apos;---TABLE_NAME---&apos; 
        ///                AND tc.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos; 
        ///	     ) tc ON tc.CONSTRAINT_NAME = cu.CONSTRAINT_NAME.
        /// </summary>
        internal static string GetTablesPrimaryKeyScript {
            get {
                return ResourceManager.GetString("GetTablesPrimaryKeyScript", resourceCulture);
            }
        }
    }
}
